[package]
name = "qmsg-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
libc = "0.2.126"
os_pipe = "1.0.1"
tokio = { version = "1.19.2", features = ["full"] }
